/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PlatformManagerRole;

import userinterface.SystemAdminWorkArea.*;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Platform;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    
    Network net;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer,Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;

        
        net = new Network();
        for (Network network : system.getNetworkList()) {
            for (Enterprise en : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getName().equals(en.getName())){
                    net  = network;
                }
                
            }
        }
        populateTable(net);
        
    }

    private void populateTable(Network nett) {
        
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        
        
        
        for(Enterprise enter : nett.getEnterpriseDirectory().getEnterpriseList()){
            Object[] row = new Object[2];
            row[0] = enter;
            //row[1] = net;
            row[1] = enter.getEnterpriseType().getValue();
            model.addRow(row);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));

        enterpriseJTable.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Enterprise Name", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);

        submitJButton.setBackground(new java.awt.Color(255, 204, 153));
        submitJButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 102, 0));
        submitJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/image/hint.png"))); // NOI18N
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 153, 51));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/image/back.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setBackground(new java.awt.Color(255, 204, 153));
        deleteJButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        deleteJButton.setForeground(new java.awt.Color(255, 102, 0));
        deleteJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/image/delete.png"))); // NOI18N
        deleteJButton.setText("Delete Enterprise");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Manage Enterprise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deleteJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(362, 362, 362))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        String mess = "The platform manager is responsible for supervising and managing the performance of each enterprise:\n"
                + " Food Retailer, Cotsume Retailer, Delivery Company.\n "
                + "If it is found that the performance of the enterprise is not good,\n"
                + " the platform manager has the right to remove the enterprise \n "
                + "and close the operation of the enterprise in this region.\n\n"
                +"Evaluation Methods: \n"
                +"For Retailer:\n"
                + "The evaluation score of all products is below 3; \n"
                + "The retailer has not delivered more than 5 times within 10 days after payment; \n"
                + "Has been complained about quality problems for more than 5 times.\n\n "
                +"For Delivery Company: \n"
                + "The deliveryman was not assigned within 2 days more than 5 times;\n"
                + "The Express items were damaged more than 10 times;\n"
                + "The Express items were lost more than 5 times. \n";
        JScrollPane sp = new JScrollPane(new JTextArea(mess,10,60));
        Object label = null;
        
        
        JOptionPane.showMessageDialog(null, new Object[]{label,sp},"Enterprise Evaluation Methods",INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        int selectedrow = enterpriseJTable.getSelectedRow(); // get selected row number
        if(selectedrow >= 0){
            //Network n = (Network)enterpriseJTable.getValueAt(selectedrow, 1);
            Enterprise en = (Enterprise)enterpriseJTable.getValueAt(selectedrow, 0);
           
            if(enterpriseJTable.getValueAt(selectedrow, 1).equals("Platform")){
                JOptionPane.showMessageDialog(null,"Cannot delete Platform of this network.");
                return;
            }
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this enterprise?","Warning",JOptionPane.YES_NO_OPTION);
            //return int value
            if (dialogResult == JOptionPane.YES_OPTION){
                //ecosystem.getUserAccountDirectory().removeUserAccount(a.toString());
                //Network a = (Network)networkJTable.getValueAt(selectedrow, 0);
                net.getEnterpriseDirectory().getEnterpriseList().remove(en);
                try{
                for (UserAccount userAccount : en.getUserAccountDirectory().getUserAccountList()) {
                    en.getUserAccountDirectory().removeUserAccount(userAccount.getUsername());
                }
                for(Employee e :en.getEmployeeDirectory().getEmployeeList()){
                    en.getEmployeeDirectory().deleteEmployee(e);
                }
                }catch(Exception e){
                    
                }
                
               
                
                JOptionPane.showMessageDialog(null,"This enterprise has been deleted.");
                populateTable(net);
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select any row.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
