/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PlatformManagerRole;

import Business.CustomerManager.CustomerManager;
import Business.CustomerManager.CustomerManagerDirectory;
import userinterface.DeliveryManagerRole.*;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import userinterface.DeliveryManRole.*;
import Business.EcoSystem;
import Business.Enterprise.DeliveryCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PlatformEnterprise;
import Business.Organization.DeliveryCompanyOrganization;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class PlatformManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount user;
    private Enterprise enterprise;
    //private Organization organization;
    private CustomerManagerDirectory custD;
    private PlatformEnterprise Denterprise;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public PlatformManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Enterprise enterprise ) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        //this.organization =  organization;
        Denterprise = new PlatformEnterprise(enterprise.getName(), new CustomerManagerDirectory());
        custD = Denterprise.getCustomerManagerDirectory();
        
        //先设一个customer manager
        custD = Denterprise.getCustomerManagerDirectory();
        custD.createCustomerManager(new CustomerManager("Elem","deliveryman1","deliveryman1!"));
        
        valueLabel.setText(enterprise.getName());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageDeliverymanJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel.setText("Platform:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, 30));

        valueLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 130, -1));

        manageDeliverymanJButton.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        manageDeliverymanJButton.setText("Customer Service");
        manageDeliverymanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDeliverymanJButtonActionPerformed(evt);
            }
        });
        add(manageDeliverymanJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageDeliverymanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDeliverymanJButtonActionPerformed
        //system.getWorkQueue()
        CustomerServiceJPanel p  = new CustomerServiceJPanel(userProcessContainer,Denterprise,enterprise);
        userProcessContainer.add("CSJPanel",p);
        CardLayout layout =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDeliverymanJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton manageDeliverymanJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
