/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CostumeOrderMngRole;

import Business.EcoSystem;
import Business.Enterprise.CostumeEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.CostumeOrderMng;
import Business.Organization.Organization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.CustomerWorkAreaJPanel.WorkRequestJPanel;

/**
 *
 * @author xuexianxie
 */
public class CostumeOrderMngWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private CostumeOrderMng CostumeOrderMng;
    public ArrayList<WorkRequest> orderList;
    public Enterprise enterprise;
    public CostumeEnterprise costumeEnterprise;
    public WorkQueue wq;
    public WorkRequest wr;
    /**
     */
    public CostumeOrderMngWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        this.CostumeOrderMng = (CostumeOrderMng)organization;
        costumeEnterprise = (CostumeEnterprise)enterprise;
        
        orderList = new ArrayList<WorkRequest>();
        wq = business.getWorkQueue();
        
        for(WorkRequest wr: wq.getWorkRequestList()){          
            if(wr.getOrderList().get(0).getEnt() == costumeEnterprise){
                if(wr.getType() != null){
                    if(wr.getStatus().equals("Placed Order")){
                        orderList.add(wr);
                    }
                    else if(wr.getStatus().equals("Send_Back")){
                        orderList.add(wr);
                    }
                    
                }
                else{
                    if(wr.getStatus().equals("Placed Order")){
                        orderList.add(wr);
                    }
                }
                
            }
        }
        
        populateTable();
    }
    
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
        
        
        model.setRowCount(0);
        for(WorkRequest w: orderList){
            Object[] row = new Object[5];
            row[0] = w.getCustomer();
            row[1] = w.getRequestDate();
            row[2] = w.getStatus();
            row[3] = w.getType();
            row[4] = w.getPrice();
            System.out.print("WR SIZE: "+w.getOrderList().size());
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setForeground(new java.awt.Color(255, 102, 0));

        OrderTable.setBackground(new java.awt.Color(255, 204, 153));
        OrderTable.setFont(new java.awt.Font("YuGothic", 0, 12)); // NOI18N
        OrderTable.setForeground(new java.awt.Color(255, 102, 0));
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Order Time", "Status", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrderTable);
        if (OrderTable.getColumnModel().getColumnCount() > 0) {
            OrderTable.getColumnModel().getColumn(0).setResizable(false);
            OrderTable.getColumnModel().getColumn(1).setResizable(false);
            OrderTable.getColumnModel().getColumn(2).setResizable(false);
            OrderTable.getColumnModel().getColumn(3).setResizable(false);
            OrderTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel1.setText("Order Table");

        btnView.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(btnView)))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnView)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = OrderTable.getSelectedRow();
        if(row< 0){
            JOptionPane.showMessageDialog(null, "Please select one item!");
            
        }
        else{
            
            wr = orderList.get(row);
            OrderDetailJPanel pop = new OrderDetailJPanel(userProcessContainer, business, userAccount, costumeEnterprise, wr);
            userProcessContainer.add("WorkRequestJPanel", pop);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            

        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
