/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManagerRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Enterprise.DeliveryCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.DeliveryOrganization;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BY
 */
public class assignDeliverJPanel extends javax.swing.JPanel {

    /**
     * Creates new form assignDeliverJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    
    private Enterprise Denterprise;
    private EcoSystem business;
    private ArrayList<WorkRequest> orderList;
    public WorkQueue wq;
    
    
    public assignDeliverJPanel(JPanel userProcessContainer, Enterprise Denterprise,UserAccount userAccount,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Denterprise = Denterprise;
        this.business = business;
        this.userAccount = userAccount;
        orderList = new ArrayList<WorkRequest>();
        //显示的work request
        wq = business.getWorkQueue();
        for(WorkRequest wr: wq.getWorkRequestList()){
            if(wr.getStatus().equals("Ready")){
                orderList.add(wr);
            }
        }
        
        DeliveryCompanyEnterprise de = (DeliveryCompanyEnterprise)Denterprise;
        jComboBox1.removeAllItems();
        for (DeliveryMan d : de.getDeliveryManDirectory().getdList()) {
            jComboBox1.addItem(d.toString());
        }
        displayTable();
    }
    
    public boolean haveorder(UserAccount ua){
        for(WorkRequest wr: business.getWorkQueue().getWorkRequestList()){
            System.out.print("\n"+" enterprise : "+wr.getCustomer());
            System.out.print(" enterprise : "+wr.getDeliverman());
            System.out.print(" enterprise : "+wr.getEnterprise()+"\n");
            if(wr.getDeliverman() != null){
                System.out.print(" |||| : "+wr.getDeliverman());
                System.out.print(" |||| : "+ua);
                if(wr.getDeliverman() == ua){
                    return true;
                }
            }
            
        }
        
        return false;
        
    }
    public final void displayTable(){
        //
        //ArrayList<WorkRequest> pd = new ArrayList();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        /*
        for(WorkRequest a : userAccount.getWorkQueue().getWorkRequestList()){
            if(a.getStatus().equals("Ready") || a.getStatus().equals("Delivering"))
                pd.add(a);
            
        }*/
        //另一种方法
        
        for(WorkRequest a :orderList){
            Object row[] = new Object[5];
            
            row[0] = a.getCustomer(); 
            row[1] = a.getEnterprise();  
            row[2] = a.getDeliverman();
            row[3] = a.getStatus();
            //?request time 无
            SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
            row[4] = df.format(a.getRequestDate());
            
            dtm.addRow(row);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 204, 153));

        jTable1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Receiver", "Deliver Man", "Status", "Request Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Orders Assignment");

        btnAssign.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAssign.setText("Assignment");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/image/back.png"))); // NOI18N
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/image/kuaidi.png"))); // NOI18N
        jLabel2.setToolTipText("Choose a delivery man");

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addComponent(btnAssign))
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAssign))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        int selectedrow = jTable1.getSelectedRow(); // get selected row number
        if(selectedrow >= 0){
            WorkRequest a = orderList.get(selectedrow); //received 
            //UserAccount selectedm = new UserAccount();
            String  selected =(String)jComboBox1.getSelectedItem();
            //find the combobox selected deliver man name - user account username 比较username？
            
            
//seleted order has assigned delivery man
            //没有指定的话，a.getDeliverman()报错，try, catch!!
            
            
                    if(a.getDeliverman() != null){
                        JOptionPane.showMessageDialog(null, "The order has assigned to another delivery man.");
                        return;
                    }
 //selected deliveryman has assigned order           
            //|| a.getReceiver().equals(r)
            //find the user account of the delivery man, add work request on its work queue
            


            
            for(UserAccount r:Denterprise.getUserAccountDirectory().getUserAccountList()){
                System.out.print("111111: "+ selected);
                System.out.print("111111 "+ r.getUsername());
                if(r.getUsername().equals(selected)){
                    //seleted useraccount(deliveryman) has no work queue, then YES!
                    //没有指定的话，r.getWorkQueue()报错，try, catch!!
//                    if(!r.getWorkQueue().getWorkRequestList().isEmpty()){
                    System.out.print("2222");
                    if(a.getStatus().equals("Ready")){
                        
                        if(haveorder(r)){
                            
                            JOptionPane.showMessageDialog(null, " The deliveryman has assigned a order.  ");
                            return;
        
                        }
                        a.setDeliverman(r);
                        System.out.print("deliveryman: "+r.getUsername());
                        a.setStatus("Wait");
                        JOptionPane.showMessageDialog(null, "The order is assigned to the delivery company, waiting for assignment.");
                        displayTable();
                    }else{
                        JOptionPane.showMessageDialog(null, "The previous process must be completed first");
                    }
                   
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select any row.","Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
