/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManagerRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import userinterface.DeliveryManRole.*;
import Business.EcoSystem;
import Business.Enterprise.DeliveryCompanyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.DeliveryOrganization;
import Business.Organization.Organization;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DeliveryManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount user;
    private Enterprise enterprise;
    //private Organization organization;
    private DeliveryManDirectory custD;
    private EcoSystem business;
    //private DeliveryCompanyEnterprise Denterprise;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DeliveryManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Enterprise enterprise ,EcoSystem business) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        this.business = business;
        //this.organization =  organization;
        //Denterprise =(DeliveryCompanyEnterprise)enterprise;
     
       
        valueLabel.setText(enterprise.getName());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignDeliverymanJButton = new javax.swing.JButton();
        manageDeliverymanJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignDeliverymanJButton.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        assignDeliverymanJButton.setText("Assignment of delivery man");
        assignDeliverymanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDeliverymanJButtonActionPerformed(evt);
            }
        });
        add(assignDeliverymanJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 240, -1));

        manageDeliverymanJButton.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        manageDeliverymanJButton.setText("Manage delivery man");
        manageDeliverymanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDeliverymanJButtonActionPerformed(evt);
            }
        });
        add(manageDeliverymanJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 210, -1));

        enterpriseLabel.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        enterpriseLabel.setText("Delivery Company:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, 30));

        valueLabel.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/image/37d5237749e5b8cc66dc0aa4f329206.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 430, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void assignDeliverymanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDeliverymanJButtonActionPerformed
        assignDeliverJPanel p  = new assignDeliverJPanel(userProcessContainer,enterprise,user,business); //user: manager
        userProcessContainer.add("ADJPanel",p);
        CardLayout layout =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_assignDeliverymanJButtonActionPerformed

    private void manageDeliverymanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDeliverymanJButtonActionPerformed
        //system.getWorkQueue()
        manageDeliverymanJPanel p  = new manageDeliverymanJPanel(userProcessContainer,enterprise);//organization
        userProcessContainer.add("MOJPanel",p);
        CardLayout layout =  (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDeliverymanJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignDeliverymanJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDeliverymanJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
