/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManagerRole;


import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Enterprise.DeliveryCompanyEnterprise;
import Business.Enterprise.Enterprise;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BY
 */

public class manageDeliverymanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    private JPanel userProcessContainer;
    private DeliveryManDirectory custD;
    private DeliveryCompanyEnterprise Denterprise;
    
    public manageDeliverymanJPanel(JPanel userProcessContainer,DeliveryCompanyEnterprise Denterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Denterprise = Denterprise;
        custD = Denterprise.getDeliveryManDirectory();
        populateTable();
    }
    
    public final void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        for(DeliveryMan a : custD.getdList()){
            Object row[] = new Object[2];
            row[0] = a; 
            row[1] = a.getTel();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        createCbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "TEL Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        deleteBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        deleteBtn.setText("Delete Delivery Man");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        createCbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        createCbtn.setText("Create Delivery Man");
        createCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCbtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(backbtn)
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createCbtn)
                    .addComponent(deleteBtn))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createCbtn)
                                .addGap(112, 112, 112)
                                .addComponent(deleteBtn)))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedrow = jTable1.getSelectedRow(); // get selected row number
        if(selectedrow >= 0){
            DeliveryMan a = (DeliveryMan)jTable1.getValueAt(selectedrow, 0);

            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this DeliveryMan?","Warning",JOptionPane.YES_NO_OPTION);
            //return int value
            if (dialogResult == JOptionPane.YES_OPTION){
                //ecosystem.getUserAccountDirectory().removeUserAccount(a.toString());
                
                custD.deleteDeliveryMan(a);
                JOptionPane.showMessageDialog(null,"This DeliveryMan has been deleted.");
                populateTable();
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select any row.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void createCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCbtnActionPerformed
        
        CreateDeliverymanJPanel createpanel = new CreateDeliverymanJPanel(userProcessContainer,Denterprise); //无DeliveryManDirectory？
        userProcessContainer.add("CreateRJPanel" ,createpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createCbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton createCbtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
